// 学习中心知识卡片数据。
// 写作约定：面向患者家属与患者本人，温和、教育性；
// 不提供诊断或调药建议——指标解读归医疗团队，用药决策遵医嘱。
// source 为 null 时界面显示「本应用使用说明」。

import type { Card } from "./learningContent";

const sources = {
  ferritin: {
    name: "MedlinePlus · 铁蛋白检测",
    url: "https://medlineplus.gov/lab-tests/ferritin-blood-test/",
  },
  a1c: { name: "MedlinePlus · A1C", url: "https://medlineplus.gov/a1c.html" },
  jia: {
    name: "NIAMS · JIA 知识",
    url: "https://www.niams.nih.gov/health-topics/juvenile-arthritis",
  },
  mas: {
    name: "NIAMS · JIA 研究与资源",
    url: "https://www.niams.nih.gov/health-topics/juvenile-arthritis/more-info",
  },
  crp: {
    name: "MedlinePlus · CRP 检测",
    url: "https://medlineplus.gov/lab-tests/c-reactive-protein-crp-test/",
  },
  esr: {
    name: "MedlinePlus · 血沉（ESR）检测",
    url: "https://medlineplus.gov/lab-tests/erythrocyte-sedimentation-rate-esr/",
  },
  cbc: {
    name: "MedlinePlus · 全血细胞计数",
    url: "https://medlineplus.gov/lab-tests/complete-blood-count-cbc/",
  },
  glucose: {
    name: "MedlinePlus · 血糖检测",
    url: "https://medlineplus.gov/lab-tests/blood-glucose-test/",
  },
  ketones: {
    name: "MedlinePlus · 血酮检测",
    url: "https://medlineplus.gov/lab-tests/ketones-in-blood/",
  },
  niddkHypo: {
    name: "NIDDK · 低血糖",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/low-blood-glucose-hypoglycemia",
  },
  niddkOverview: {
    name: "NIDDK · 糖尿病概览",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview",
  },
  printo: {
    name: "PRINTO · 儿童风湿病家庭资料",
    url: "https://www.printo.it/pediatric-rheumatology/GB/intro",
  },
};

export const topics: string[] = [
  "sJIA / MAS",
  "检验知识",
  "糖尿病",
  "用药常识",
  "照护记录",
  "就诊沟通",
];

export const cards: Card[] = [
  // —— 原有卡片（id 不变，保持在最前）——
  {
    id: "ferritin",
    topic: "检验知识",
    title: "Ferritin 是什么？",
    text: "Ferritin 是铁蛋白。铁蛋白检测帮助了解体内铁储存；结果也可能受到炎症等因素影响，不能用一个数值单独判断疾病，需结合临床背景、由医疗团队解读。",
    takeaway: "读报告时，同时保留单位、日期和报告来源。",
    source: sources.ferritin,
  },
  {
    id: "a1c",
    topic: "糖尿病",
    title: "HbA1c 与当天血糖不同",
    text: "HbA1c（糖化血红蛋白）反映约过去三个月的平均血糖水平，不是某一餐之后的即时血糖。它帮助医生判断一段时间的控制情况，不能替代日常血糖记录。",
    takeaway: "记录血糖时注明空腹、餐后或随机背景。",
    source: sources.a1c,
  },
  {
    id: "jia",
    topic: "sJIA / MAS",
    title: "先认识 JIA 这个名字",
    text: "JIA 是 juvenile idiopathic arthritis，即幼年特发性关节炎。sJIA 是其中的全身型，症状可涉及关节以外的部位。",
    takeaway: "把症状发生的时间与变化记录下来，方便复诊沟通。",
    source: sources.jia,
  },
  {
    id: "mas",
    topic: "sJIA / MAS",
    title: "为什么要关注变化？",
    text: "MAS（巨噬细胞活化综合征）是 sJIA 的一种少见但危险的并发症。学习术语有助于沟通，判断是否发生仍需要医疗团队评估。",
    takeaway: "应用提醒是沟通线索，不是自行确诊或调药的依据。",
    source: sources.mas,
  },
  {
    id: "record",
    topic: "照护记录",
    title: "计划与实际发生，要分开记",
    text: "“计划今晚服药”和“今晚已经服药”是两件事。本应用用照护计划保存安排，用事件记录实际发生的治疗。分开记录能减少照护沟通中的误差。",
    takeaway: "记录事件时写清时间；住院标签只描述这一次事件。",
    source: null,
  },
  {
    id: "risk",
    topic: "照护记录",
    title: "没有提醒，就一定安全吗？",
    text: "本应用的规则只覆盖部分场景。“未触发提醒”“未启用风险评估”和“没有数据”含义不同，不能互相替代。任何疑虑都应交给医疗团队判断。",
    takeaway: "就诊时带上原始报告和变化记录，不只看颜色。",
    source: null,
  },

  // —— sJIA / MAS ——
  {
    id: "fever-pattern",
    topic: "sJIA / MAS",
    title: "弛张热有什么特点？",
    text: "sJIA 的发热常呈弛张热：每天固定时段（多见傍晚）升到很高，又能自行退回正常；发热时孩子明显不适，热退后又像没事。把每天发热的时间和最高体温记下来，是医生判断病情的重要线索。",
    takeaway: "记录每次发热的时间与最高体温。",
    source: sources.jia,
  },
  {
    id: "rash-fever",
    topic: "sJIA / MAS",
    title: "皮疹为什么跟着发热来？",
    text: "sJIA 的皮疹多为淡红色斑疹，常在发热时出现、热退后变淡或消失，通常不痒。皮疹本身不可怕，但它是全身炎症活动的外在表现之一。出现时拍照并记下当天体温，能帮助医生把皮疹与发热联系起来看。",
    takeaway: "皮疹出现时拍照，并记下当天体温。",
    source: sources.jia,
  },
  {
    id: "systemic-meaning",
    topic: "sJIA / MAS",
    title: "“全身型”是什么意思？",
    text: "全身型指炎症不只影响关节，还可能累及全身：发热、皮疹、淋巴结肿大、肝脾增大、心包或胸膜炎症都可能出现，早期关节症状有时反而不明显。它远比“关节炎”三个字涵盖的范围更大，随访项目也更多。",
    takeaway: "随访时主动说起发热皮疹，不只谈关节。",
    source: sources.jia,
  },
  {
    id: "joint-swelling",
    topic: "sJIA / MAS",
    title: "关节肿痛怎么记录？",
    text: "记录关节症状时写清三件事：哪个关节、什么表现（肿、痛、伸不直）、持续多久。晨起僵硬多少分钟能缓解尤其值得记。是否影响走路、握笔、上下楼梯，这些细节比一句“腿疼”更能帮助医生判断疾病活动度。",
    takeaway: "记关节症状：部位、表现、持续时间。",
    source: sources.jia,
  },
  {
    id: "active-remission",
    topic: "sJIA / MAS",
    title: "什么是活动期与缓解期？",
    text: "活动期指疾病处于活跃状态，可能有发热、皮疹、关节肿痛或炎症指标升高；缓解期指症状安静、指标趋于正常。缓解不等于治愈，多数孩子仍需用药和随访来维持。两个阶段可能反复交替，持续记录能帮医生看清孩子处在哪个阶段。",
    takeaway: "指标好转后仍按计划复诊，不自行减停。",
    source: sources.jia,
  },
  {
    id: "ferritin-inflammation",
    topic: "sJIA / MAS",
    title: "铁蛋白为何随炎症升高？",
    text: "铁蛋白除了反映铁储存，还是一种炎症敏感指标：感染、慢性炎症或 sJIA 活动时都可能升高。随访中医生会结合体温、皮疹和其他指标一起看它的变化。单独一个高数值说明不了全部问题，需结合背景、由医疗团队解读。",
    takeaway: "把历次铁蛋白结果按时间排起来看趋势。",
    source: sources.ferritin,
  },
  {
    id: "morning-stiffness",
    topic: "sJIA / MAS",
    title: "晨僵是什么感觉？",
    text: "晨僵指早晨醒来时关节发紧、活动不灵便，活动一段时间后逐渐缓解，是关节炎的常见表现。僵硬持续多久能反映炎症活跃程度。记录“起床后多久才能正常走路、握拳”，这个分钟数是复诊时很实用的信息。",
    takeaway: "记录晨僵大约持续多少分钟。",
    source: sources.jia,
  },
  {
    id: "mas-urgent",
    topic: "sJIA / MAS",
    title: "哪些变化要及时就医？",
    text: "如果发热从间歇变成持续不退、孩子精神明显变差、出现瘀青或出血、原有症状突然加重，都可能提示病情变化，包括 MAS 等并发症的可能。这时不要等待应用提醒，也不要自行判断，应联系医疗团队或及时就医，由医生评估处理。",
    takeaway: "发热性质改变或状态变差，立即联系医生。",
    source: sources.mas,
  },
  {
    id: "followup-longterm",
    topic: "sJIA / MAS",
    title: "为什么要长期随访？",
    text: "sJIA 可能持续数年、时轻时重。即使症状缓解，体内炎症仍可能悄悄活动，部分孩子还会出现生长、骨骼或药物方面的问题。定期随访让医生根据趋势调整方案，也让家人有机会把疑问一条条问清楚，是孩子长期健康的安全网。",
    takeaway: "把随访日期写进日历，提前整理问题。",
    source: sources.mas,
  },
  {
    id: "activity-joint",
    topic: "sJIA / MAS",
    title: "孩子要完全静养吗？",
    text: "发热急性期需要休息，但长期完全不动反而会让关节更僵、肌肉变弱。多数孩子在病情允许时可以温和活动、正常上学，具体强度由医生和康复师按关节情况建议。记录活动后关节的反应，能帮助团队给出更合适的运动建议。",
    takeaway: "记录活动后的关节反应，复诊时反馈。",
    source: sources.printo,
  },

  // —— 检验知识 ——
  {
    id: "crp",
    topic: "检验知识",
    title: "CRP 升高说明什么？",
    text: "CRP（C 反应蛋白）是肝脏在炎症活跃时产生的蛋白。感染、外伤、关节炎活动都可能让它升高，所以它提示“体内有炎症”，但不能单独说明炎症来自哪里、严重到什么程度。医生会结合症状和其他检查判断，单次升高不必过度紧张。",
    takeaway: "看 CRP 时，同时记下当天有无发热。",
    source: sources.crp,
  },
  {
    id: "esr",
    topic: "检验知识",
    title: "血沉（ESR）看什么？",
    text: "血沉是红细胞在试管中下沉的速度，炎症活跃时往往加快。它变化比 CRP 慢，适合观察一段时间的炎症趋势，常与 CRP 一起看。贫血、年龄等也会影响结果，同样需要结合背景、由医疗团队解读，而不是只看一次高低。",
    takeaway: "ESR 与 CRP 放在一起看，趋势更清楚。",
    source: sources.esr,
  },
  {
    id: "cbc",
    topic: "检验知识",
    title: "全血细胞计数查什么？",
    text: "全血细胞计数（CBC）一次给出红细胞、白细胞、血红蛋白和血小板的基本情况，是随访中最常见的检查。它能提示贫血、感染迹象或血液变化。报告每项都有参考范围，但儿童标准与成人不同，解读应交给医疗团队。",
    takeaway: "保留 CBC 原始报告，复诊时一并携带。",
    source: sources.cbc,
  },
  {
    id: "platelets",
    topic: "检验知识",
    title: "血小板高低说明什么？",
    text: "血小板参与止血凝血，包含在全血细胞计数里。炎症活跃时血小板常常升高；如果反而明显下降，医生会特别关注，因为这可能提示病情变化。它只是拼图的一块，无论高低都要结合症状和其他指标，由医疗团队综合解读。",
    takeaway: "血小板明显变化时，主动问医生原因。",
    source: sources.cbc,
  },
  {
    id: "fibrinogen",
    topic: "检验知识",
    title: "纤维蛋白原是什么？",
    text: "纤维蛋白原是参与凝血的一种蛋白质。炎症活跃时它可能升高；而在 MAS 等严重并发症中，它可能因消耗而反常下降。家长不必记住参考数值，只需知道医生常把它纳入病情评估，结果应由医疗团队结合整体情况解读。",
    takeaway: "报告里有这项时，连同其他结果一起保存。",
    source: sources.printo,
  },
  {
    id: "ast",
    topic: "检验知识",
    title: "AST 升高代表什么？",
    text: "AST 是存在于肝脏、肌肉等组织中的一种酶，升高提示这些组织可能受到损伤。sJIA 随访中，它既可能反映疾病活动，也可能与药物影响有关，医生会定期监测。单独一次升高不必恐慌，但值得向医生问清原因、按建议复查。",
    takeaway: "AST 异常时，问医生是否需要复查。",
    source: sources.printo,
  },
  {
    id: "ldh",
    topic: "检验知识",
    title: "LDH 是什么指标？",
    text: "LDH 广泛存在于全身细胞中，细胞损伤增多时它会升高，因此是个敏感但不特异的信号：很多情况都能让它上升。医生评估疾病活动度或并发症风险时会参考它。它不能单独指向任何一种疾病，需结合背景、由医疗团队解读。",
    takeaway: "把 LDH 放进趋势表，看方向不看单点。",
    source: sources.printo,
  },
  {
    id: "triglycerides",
    topic: "检验知识",
    title: "甘油三酯为何也要看？",
    text: "甘油三酯是血脂的一种。sJIA 随访中医生有时会关注它，因为明显升高可能与炎症状态或并发症评估有关；它也容易受进食影响，所以报告要结合是否空腹等背景来看。数值高低由医疗团队解读，不必自己对照参考值下结论。",
    takeaway: "血脂检查前，按医嘱确认是否空腹。",
    source: sources.printo,
  },
  {
    id: "units-range",
    topic: "检验知识",
    title: "单位和参考范围怎么看？",
    text: "同一指标在不同医院可能用不同单位，参考范围也因年龄、性别和实验室而异。比较两次结果前，先确认单位和检测方法一致。报告上的箭头只表示超出该实验室的参考范围，不代表严重程度，具体解读要结合临床背景。",
    takeaway: "记录数值时，连同单位一起记下来。",
    source: sources.cbc,
  },
  {
    id: "trend-single",
    topic: "检验知识",
    title: "趋势和单次哪个更重要？",
    text: "一次异常数值可能来自生理波动、采血状态或检测差异，而一连串结果的变化方向更能说明病情走向。医生复诊时最需要的往往不是某个最高值，而是趋势。把历次结果按日期整理好，比记住某一次的具体数字有用得多。",
    takeaway: "就诊带历次报告，不只带最近一次。",
    source: sources.crp,
  },
  {
    id: "draw-context",
    topic: "检验知识",
    title: "采血背景影响结果吗？",
    text: "会。是否空腹、发热第几天、用药后多久，都可能影响检验结果：血糖血脂受进食影响，炎症指标随病情波动。采血前可以询问本次是否需要空腹，并在记录中注明背景。这些细节能让医生日后对比时解读得更准确。",
    takeaway: "采血记录注明空腹与否和发热天数。",
    source: sources.glucose,
  },

  // —— 糖尿病 ——
  {
    id: "glucose-context",
    topic: "糖尿病",
    title: "血糖值要看测量背景",
    text: "同样是 8 mmol/L，空腹测和刚吃完饭测含义完全不同。血糖记录一般分空腹、餐前、餐后、随机几种背景，各自有不同的参考意义。记录时标清背景，趋势才有可比性，医生才能据此判断。具体目标范围请遵医疗团队的个体化建议。",
    takeaway: "每次测血糖，先标背景再看数值。",
    source: sources.glucose,
  },
  {
    id: "hypo-signs",
    topic: "糖尿病",
    title: "低血糖有哪些信号？",
    text: "低血糖常见信号包括心慌、手抖、出汗、饥饿、头晕、脸色苍白；孩子可能表现为烦躁、哭闹或喊没力气，婴幼儿不会表达，更要留意反常状态。怀疑低血糖时按医疗团队教过的方法处理，并把发生时间和当时情况记下来。",
    takeaway: "记住孩子的低血糖表现，告知照护者。",
    source: sources.niddkHypo,
  },
  {
    id: "hypo-treat",
    topic: "糖尿病",
    title: "低血糖时一般怎么办？",
    text: "常识做法是立即让孩子进食或饮用含快速糖分的食品，休息片刻后复测；具体用量和流程应遵循医疗团队给出的方案，本应用不提供剂量建议。若孩子意识不清或无法吞咽，不要强行喂食，应立即联系急救或医疗团队。",
    takeaway: "提前问清低血糖处理方案，随身备糖。",
    source: sources.niddkHypo,
  },
  {
    id: "hyper-signs",
    topic: "糖尿病",
    title: "高血糖有哪些信号？",
    text: "高血糖常见表现是口渴、多饮、多尿、容易疲倦；持续升高时孩子可能恶心、腹痛、呼吸深快。这些信号提示要按医疗团队事先给出的方案处理，而不是自行调整胰岛素剂量。反复出现高血糖，应记录数值与背景，复诊时反馈。",
    takeaway: "高血糖反复出现，记录后向医生反馈。",
    source: sources.glucose,
  },
  {
    id: "ketones",
    topic: "糖尿病",
    title: "酮体是什么？",
    text: "当身体缺乏足够胰岛素、转而大量分解脂肪时，会产生酮体。生病、呕吐或持续高血糖时，医生可能建议测血酮或尿酮。酮体明显升高可能发展成危险的酮症酸中毒，那是需要医疗团队及时处理的急症，不能在家观察等待。",
    takeaway: "生病日或持续高血糖，按医嘱测酮体。",
    source: sources.ketones,
  },
  {
    id: "insulin-basics",
    topic: "糖尿病",
    title: "胰岛素是做什么的？",
    text: "胰岛素帮助血液中的葡萄糖进入细胞、为身体供能。1 型糖尿病孩子的身体几乎不再分泌胰岛素，需要终身外源补充。胰岛素的种类、剂量和注射时间都是个体化方案，必须严格遵医嘱，任何调整都应先与医疗团队沟通。",
    takeaway: "胰岛素方案照医嘱执行，不自行增减。",
    source: sources.niddkOverview,
  },
  {
    id: "carbs-glucose",
    topic: "糖尿病",
    title: "碳水和血糖什么关系？",
    text: "碳水化合物消化后会转化为葡萄糖，是影响餐后血糖最直接的食物成分，米饭、面食、水果、牛奶都含碳水。了解常见食物的碳水含量，有助于配合医嘱安排胰岛素与进食时间。具体碳水计算方法请遵医疗团队指导。",
    takeaway: "记录正餐大致碳水，配合血糖一起看。",
    source: sources.niddkOverview,
  },
  {
    id: "exercise-glucose",
    topic: "糖尿病",
    title: "运动会影响血糖吗？",
    text: "会。运动时肌肉消耗葡萄糖，血糖往往下降，有时运动结束几小时后还在降；剧烈运动偶尔也会让血糖先升后降。运动前后测血糖、随身带糖、提前告知老师注意事项，都是常见做法，具体安排请遵医疗团队的个体化建议。",
    takeaway: "运动前后各测一次血糖并记录。",
    source: sources.niddkHypo,
  },
  {
    id: "sick-day",
    topic: "糖尿病",
    title: "生病日血糖为何会乱？",
    text: "发热、感染时，身体分泌的应激激素会推高血糖，即使吃得少也可能升高；呕吐腹泻又让血糖难以预测。生病日通常需要更勤地监测，并按医疗团队事先给出的生病日方案处理。持续呕吐、无法进食或酮体升高时，应及时联系医生。",
    takeaway: "提前向医生要一份生病日处理方案。",
    source: sources.niddkHypo,
  },

  // —— 用药常识 ——
  {
    id: "follow-prescription",
    topic: "用药常识",
    title: "为什么不建议自行停药？",
    text: "症状好转常常只是疾病被药物控制住了，并不代表疾病已经消失。自行停药或减量可能让炎症反弹，甚至更难控制。是否减量、何时减量，只能由医疗团队根据症状和检查趋势决定，具体用药严格遵医嘱。有顾虑时把担心记下来，复诊当面问医生。",
    takeaway: "想减停药时，先记下来问医生。",
    source: sources.jia,
  },
  {
    id: "mtx-basics",
    topic: "用药常识",
    title: "甲氨蝶呤是什么药？",
    text: "甲氨蝶呤是治疗 JIA 常用的改善病情药物，通过调节免疫反应控制炎症，通常每周使用一次，起效要数周到数月。用药期间医生会定期监测血常规和肝功能。具体剂量、服用方式和注意事项都必须遵医嘱，有疑问先问医生或药师。",
    takeaway: "每周用药日写进计划，避免漏服重复。",
    source: sources.jia,
  },
  {
    id: "biologics-basics",
    topic: "用药常识",
    title: "生物制剂是什么？",
    text: "生物制剂是一类针对特定炎症因子的药物，常用于常规药物控制不佳的 JIA 或 sJIA，多以注射或输液给药。使用期间要留意感染迹象，发热就诊时应主动说明正在使用生物制剂。具体药物选择、剂量和间隔必须严格遵医嘱。",
    takeaway: "就诊时主动说明孩子正用生物制剂。",
    source: sources.jia,
  },
  {
    id: "steroid-taper",
    topic: "用药常识",
    title: "激素为什么不能突然停？",
    text: "糖皮质激素能快速压制炎症，但长期使用后身体自身分泌会被抑制，突然停药可能引发危险的肾上腺问题，也可能让病情反弹。所以激素必须遵医嘱阶梯式减量，速度由医生根据病情决定。哪怕只剩很小剂量，也不要自行停掉。",
    takeaway: "激素按医嘱阶梯减量，不自行停药。",
    source: sources.jia,
  },
  {
    id: "med-storage",
    topic: "用药常识",
    title: "药物平时怎么储存？",
    text: "不同药物要求不同：有的需冷藏但不能冷冻，有的要避光，胰岛素开封前后保存温度不同，生物制剂温差过大可能失效。读一遍说明书上的储存项，外出用保温袋和冰袋，回家及时放回冰箱。具体储存要求与用药方案请遵医嘱和说明书。",
    takeaway: "把每种药的储存要求抄进用药清单。",
    source: null,
  },
  {
    id: "missed-dose",
    topic: "用药常识",
    title: "漏服了怎么办？",
    text: "发现漏服时，不要凭感觉补一倍或干脆跳过。不同药物的补救规则不同：有的想起后尽快补，有的接近下次就直接跳过。正确做法是查看说明书或咨询医生、药师，并把漏服记进照护记录，复诊时如实告知。具体用药遵医嘱。",
    takeaway: "漏服后记下来，补救方案问医生药师。",
    source: null,
  },
  {
    id: "vaccine-check",
    topic: "用药常识",
    title: "打疫苗前为何先沟通？",
    text: "使用免疫抑制药物的孩子，接种疫苗的时机和种类需要特别安排：活疫苗在某些用药期间通常要暂缓，灭活疫苗也可能要挑病情稳定时接种。接种前把孩子的完整用药清单给接种医生看，并先与主治团队确认时机，具体安排遵医嘱。",
    takeaway: "接种前先与主治团队确认时机。",
    source: null,
  },
  {
    id: "side-effect-log",
    topic: "用药常识",
    title: "副作用为何要记下来？",
    text: "恶心、口腔溃疡、注射部位红肿、食欲变化，可能是药物副作用，也可能是疾病本身的表现。记下出现时间、持续多久、与用药的时间关系，医生才能判断因果、调整方案。不要因为有副作用就自行停药，先记录、再沟通，具体遵医嘱。",
    takeaway: "副作用连同发生时间和用药时间一起记。",
    source: null,
  },
  {
    id: "med-interactions",
    topic: "用药常识",
    title: "多种药同服注意什么？",
    text: "慢性病孩子常同时用多种药，偶尔还会加感冒药、退烧药。药物之间可能相互影响，例如某些退烧药与甲氨蝶呤同用需要医生知晓。加任何新药——包括保健品和中成药——之前，先告诉医生或药师孩子正在用的全部药物，具体遵医嘱。",
    takeaway: "加新药前，出示完整用药清单确认。",
    source: null,
  },
  {
    id: "med-list",
    topic: "用药常识",
    title: "为何要备用药清单？",
    text: "一份随时更新的用药清单——药名、剂量、频次、开始日期——是复诊、急诊、转诊时最省时间的工具，医生不必靠回忆拼凑，也不容易遗漏或重复。每次调整药物后立刻更新清单，旧版本留档，必要时能看出用药变化的历史。清单只是备忘，具体用药遵医嘱。",
    takeaway: "每次调药后立刻更新用药清单。",
    source: null,
  },

  // —— 照护记录 ——
  {
    id: "log-time",
    topic: "照护记录",
    title: "记时间为何这么重要？",
    text: "医生看记录时最关心什么时候发生：发热是第几天、皮疹出现在发热前还是后、服药和症状变化相隔多久。只有内容没有时间的记录，价值会大打折扣。随手记时先写时间，本应用会为事件自动打上时间戳，帮你留住这条线。",
    takeaway: "事件一发生就记，别等晚上补。",
    source: null,
  },
  {
    id: "log-unit",
    topic: "照护记录",
    title: "数字后面的单位别丢",
    text: "体温 38.5 是摄氏度，血糖 8 通常指 mmol/L，铁蛋白数值后面跟着的单位决定它怎么解读。漏掉单位的数字，复诊时可能完全无法使用。本应用的数值字段会带单位提示，填写时顺手确认；读报告时也一样，连同单位一起看。",
    takeaway: "记数字时连同单位一起写。",
    source: null,
  },
  {
    id: "log-context",
    topic: "照护记录",
    title: "记下背景，数字才有意义",
    text: "同一个血糖值，空腹测和刚吃完蛋糕测是两回事；同一次发热，退热处理前和处理后意义不同。记录时多花几秒写上背景：空腹还是餐后、发热第几天、是否刚运动过。背景完整的记录，医生才敢放心解读。",
    takeaway: "每条记录都补一句当时背景。",
    source: null,
  },
  {
    id: "symptom-elements",
    topic: "照护记录",
    title: "记症状要记哪几样？",
    text: "一条好用的症状记录包含：开始时间、具体表现、严重程度、持续多久、当时做了什么处理、之后有没有缓解。以皮疹为例：几点发现、长在哪、什么颜色、痒不痒、热退后有没有变淡。要素齐全，复诊描述就不会漏。",
    takeaway: "按“时间、表现、程度、变化”记症状。",
    source: null,
  },
  {
    id: "rash-photo",
    topic: "照护记录",
    title: "皮疹为什么要拍照？",
    text: "sJIA 的皮疹常热退后就不见了，复诊时医生看不到，一张照片能补上这个缺口：拍下皮疹的位置和形态，记下拍照时间和当天体温。照片存在本机，就诊时直接给医生看，比口头描述“好像有点红”可靠得多。",
    takeaway: "皮疹出现即拍照，注明时间和体温。",
    source: null,
  },
  {
    id: "hospital-tag",
    topic: "照护记录",
    title: "住院标签是什么意思？",
    text: "住院期间发生的事件和居家照护背景不同：用药由护士执行，检查更密集。本应用的住院标签用来标记这段特殊时期的事件，只描述这一次事件的背景，不代表疾病严重程度。出院后继续如常记录即可。",
    takeaway: "住院期间的事件记得勾选住院标签。",
    source: null,
  },
  {
    id: "share-record",
    topic: "照护记录",
    title: "怎么把记录分享给医生？",
    text: "复诊前把这段时间的记录按时间翻一遍：发热几次、皮疹出现几回、用药有没有漏、指标怎么变。就诊时直接打开应用给医生看趋势和原始报告照片。条理清楚的记录，能把有限的就诊时间留给真正重要的讨论。",
    takeaway: "复诊前先翻一遍记录，挑出重点。",
    source: null,
  },
  {
    id: "data-local",
    topic: "照护记录",
    title: "数据只存在本机吗？",
    text: "是的。本应用是演示应用，照护记录只保存在这台设备上，不会自动上传云端，也不会同步给其他家人。这意味着换设备前要自己导出或转记重要内容；也意味着分享给谁、分享什么，完全由你决定。",
    takeaway: "重要记录定期导出或另做备份。",
    source: null,
  },
  {
    id: "note-writing",
    topic: "照护记录",
    title: "备注怎么写才有用？",
    text: "备注写给未来的自己和医生看，要具体、可核对。“下午状态不好”不如“15 点体温 39.2℃，精神差，服退热药后一小时退到 37.8℃”。写清事实、少写评价；拿不准的如实写“不确定”，比省略更有价值。",
    takeaway: "备注写事实：时间、数值、处理、变化。",
    source: null,
  },
  {
    id: "review-regularly",
    topic: "照护记录",
    title: "定期回顾记录有什么用？",
    text: "记录攒起来不回顾，就只是流水账。每周花十分钟看看：发热有没有变密、皮疹有没有新变化、用药执行得怎么样。发现的规律写进问题清单带给医生；回顾也是检查记录习惯有没有松动的好机会。",
    takeaway: "每周固定十分钟回顾一周记录。",
    source: null,
  },

  // —— 就诊沟通 ——
  {
    id: "visit-prep",
    topic: "就诊沟通",
    title: "复诊前可以准备什么？",
    text: "复诊前做三件事：把原始报告和用药清单收进一个袋子；在应用里过一遍这段时间的记录，标出想请医生看的趋势；把想问的问题按重要程度列成清单。准备充分的家长，往往十分钟就能把关键问题谈完。",
    takeaway: "复诊前一天备好报告、清单、问题。",
    source: null,
  },
  {
    id: "bring-reports",
    topic: "就诊沟通",
    title: "为什么要带原始报告？",
    text: "应用里的记录是摘要，原始检验报告上有单位、参考范围和检测方法，医生需要这些细节才能准确解读。外院报告尤其重要，不同实验室的数值不能直接比较。纸质原件或清晰照片都可以，按日期排好最方便翻阅。",
    takeaway: "原始报告按日期排好，每次复诊都带。",
    source: null,
  },
  {
    id: "question-list",
    topic: "就诊沟通",
    title: "问题清单怎么列？",
    text: "想到问题随时记进清单，别等就诊前临时回忆。把最担心的排在最前面，每个问题尽量具体：不说“药要不要调”，而说“最近三周每周发热两次，需要调整吗”。问完当场把医生的回答记下来，免得回家后又模糊。",
    takeaway: "问题按担心程度排序，当场记下回答。",
    source: null,
  },
  {
    id: "fever-timeline",
    topic: "就诊沟通",
    title: "发热时间线怎么讲？",
    text: "向医生描述发热，用时间线比用形容词有效：“3 月 2 日起每天傍晚发热，最高 39℃，服退热药能退，热退后精神好，第五天开始出现皮疹。”从哪天开始、每天几次、最高多少、伴随什么变化，这四点最关键。",
    takeaway: "讲发热：起点、频次、峰值、伴随变化。",
    source: null,
  },
  {
    id: "explain-child",
    topic: "就诊沟通",
    title: "怎么向孩子解释病情？",
    text: "用孩子能懂的话说事实，不隐瞒也不夸大：“身体里有一小队卫士太兴奋了，药是帮它们安静下来的。”打针抽血前提前告知，允许害怕，完成后认真肯定。孩子理解得越多，配合度通常越好，也更愿意说出自己的不舒服。",
    takeaway: "用比喻讲事实，操作前提前告知孩子。",
    source: null,
  },
  {
    id: "changes-summary",
    topic: "就诊沟通",
    title: "怎么向医生讲变化？",
    text: "医生判断病情靠变化，不靠印象。与其说“最近不太好”，不如说“发热从一周一次变成一周三次，皮疹跟着多起来了”。就诊前在应用里对比这段和上一段记录，把最明显的两三条变化先说出来，再补充细节。",
    takeaway: "就诊先讲最明显的两三条变化。",
    source: null,
  },
  {
    id: "clarify-instructions",
    topic: "就诊沟通",
    title: "没听懂医嘱怎么办？",
    text: "没听懂很正常，医学术语对家长本来就陌生。当场请医生换个说法，或复述一遍确认：“您的意思是这个药不变、三个月后复查，对吗？”重要指示随手记进应用备注；离开诊室后想起疑问，记下来留到下次或通过正规渠道咨询。",
    takeaway: "医嘱当场复述确认，记进应用备注。",
    source: null,
  },
  {
    id: "followup-plan",
    topic: "就诊沟通",
    title: "离开诊室前确认什么？",
    text: "复诊结束前确认四件事：接下来的用药方案、下次复查的时间和项目、出现什么情况要提前就诊或联系团队、日常照护有没有新注意事项。把这些写进应用的照护计划和备注里，回家执行时就不会走样。",
    takeaway: "离诊室前确认用药、复查、预警事项。",
    source: null,
  },
];
